### ISSUE TITLE
dunno if this issue or bug

### ISSUE THREAD

**Issue by soudblox** [DZ-TM/Yagpdb.xyz#6]
ok for the message count lb, it was fine, till now its not updating, somehow

im on 8000 messages when i do -msgcount but when i do -topmessages it says that im on 4000 and not updating for other people too, its fine in my testing server somehow??

yagpdb support server? maby they wont even know y since ur the one who make the code and i did ask, and maverck said the word "we dont take responsibility for the code not on the official github" so i ask here :ee:

**Comment by DZ-TM** [comment]
Ye I just don’t recommend using it for now - when I’ve got more time (22nd Dec soonest) I’ll be refactoring codes

**Comment by DZ-TM** [comment]
Also, could you provide more details on reproducing the error? E.g. screenshots

**Comment by soudblox** [comment]
mk

**Comment by soudblox** [comment]
![image](https://user-images.githubusercontent.com/73058244/101739103-a71e9880-3af9-11eb-8360-42562e340afb.png)

it was working fine till a few days ago and i dont even realise

**Comment by soudblox** [comment]
WAIT ITS ONLY FOR ME, AND IT SHOWS FINE OTHER PEOPLE WTF LOL

**Comment by DZ-TM** [comment]
Try resetting your personal count via {{dbSet .User.ID $whateverTheDBNameIs $yourRealCount}}

**Comment by soudblox** [comment]
Ye i did I use crafter's db set xd

**Comment by DZ-TM** [comment]
so is it fixed? if so, I'll be closing this ig

**Comment by soudblox** [comment]
sure

**Comment by soudblox** [comment]
BUT WAIT, WAIT

it's now not updating for all people, it's updating for msgcount but in the lb it only shows their position but not the numbers, when i use dbGet it's also not the right value

**Comment by DZ-TM** [comment]
weird ig I'll fix / replace message count cc after a bit when I've got time

**Comment by DZ-TM** [comment]
Message count cc going yeet
